services:
  app:
    image: bjoggis/clash-together:v0.0.0-EMPTY_GIT_REPOSITORY-x86_64
    pull_policy: missing
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev,docker