name: Build latest master and deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-latest, self-hosted ]
    runs-on: ${{ matrix.os }}
    permissions:
      contents: read
      packages: write
    steps:
      - name: Setup Maven Action
        uses: s4u/setup-maven-action@v1.12.0
        with:
          java-version: 21
          java-distribution: liberica
          checkout-persist-credentials: true
          cache-enabled: false
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build with Maven
        run: mvn clean package -Pnative

      - name: Push Images to Docker Registry
        run: docker push -a bjoggis/clash-together
  manifest:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: create-manifest
        run: |
          docker manifest create bjoggis/clash-together:v0.0.0 --amend bjoggis/clash-together:v0.0.0-x86_64 --amend bjoggis/clash-together:v0.0.0-aarch_64
          docker manifest push bjoggis/clash-together:v0.0.0
          docker manifest create bjoggis/clash-together:latest --amend bjoggis/clash-together:v0.0.0-x86_64 --amend bjoggis/clash-together:v0.0.0-aarch_64
          docker manifest push bjoggis/clash-together:latest
